package org.gabrielsantana.tasks.data.source.local.model

import kotlinx.datetime.Instant
import org.gabrielsantana.tasks.data.model.Task
import org.gabrielsantana.tasks.data.source.remote.model.TaskNetworkModel
import org.gabrielsantana.tasks.data.TaskEntity

//The model is auto generated by the SQLDelight, this file is just for map function

internal fun TaskEntity.asTask(): Task = Task(
    uuid = uuid,
    deviceId = deviceId,
    title = title,
    description = description,
    isCompleted = isCompleted,
    createdAt = Instant.parse(createdAtTimestamp),
    completedAt = completedAtTimestamp?.let { Instant.parse(it) },
    updatedAt = Instant.parse(updatedAtTimestamp)
)

internal fun TaskEntity.asNetworkModel() = TaskNetworkModel(
    uuid = uuid,
    deviceId = deviceId,
    title = title,
    description = description,
    isCompleted = isCompleted,
    completedAt = completedAtTimestamp?.toString(),
    createdAt = createdAtTimestamp.toString(),
    updatedAt = updatedAtTimestamp.toString()
)